### ISSUE TITLE
Trouble installing and running - Please help

### ISSUE THREAD

**Issue by Zakb8** [openpim/web#9]
I have installed on local machine via Docker image and the "getting started" steps from openpim.org. 
I installed Postgres DB, ran the Docker command with variables
I can go to my Localhost on browser, and get the login screen.
If I type anything or click anywhere I get an error about "Invalid JSON" expected '<'.
In the chrome inspector>networking there is a GraphQL error. 

I don't care where I have to install this, but I need help getting it working. Where ever is the best place to deploy, Google cloud, digitalocean, heroku, where ever. please help, I can pay someone but don't have much.

**Comment by Zakb8** [comment]
I have emailed team@openpim.org, and haven't received any response.

**Comment by openpim** [comment]
Hi @Zakb8,

We received your email yesterday but we are not able to answer asap, usually we are answering in 1 day.

Regarding your question, seems you have wrong configuration so the system can not connect to database.
We have 2 parts inside our docker image. First is the web server (Nginx) that is hosted web page that you see (for example login page in this case) and second part is an application server that is connected to the database that you specified.
 
Here we have a situation where the web server is started and you can see the page but the application server is not started. Usually such an error is because the server can not connect to the database.
 
First that you can make is to take a look at server logs. You should make the following to see them:
1. Execute command "sudo docker container ls" and you will see all started docker processes (if you have only our system inside docker you will see only one process). And you should copy <container id>
2. Execute command "sudo docker exec -it <container id> /bin/bash". So you will go inside docker virtual machine and you will see the command prompt
3. Execute "cat server.log". I think you will see an error that the system can not connect to the database in the error log.
 
Let me describe why you can have this. Problem is that Postgres must be configured right.
1. First problem is that usually Postgres is bound to the "localhost" interface only. To change this you must go to postgresql.conf and set listen_addresses = '*'. And restart postgres.
2. Second problem is that system is running inside docker VM (so it has it own IP address), 
So you should allow connections from docker to postrges. To make this you should change postgres pg_hdba.conf and add the following line and also restart postgres:
 
host    all             all             <your host IP address>/32           md5
 
or make it as 
 
host    all             all             0.0.0.0/0           md5
 
to allow connection from all IPs
 
Also please make sure that firewall is also configured to allow the connection between docker and the database.
 
After this configuration you can restart our docker image and application server should be started. You can monitor this in the application server log file.
 
Please let me know if this helps.

Thanks,
Slava Pedak

**Comment by Zakb8** [comment]
Thank you so much for the answer !! :)
My docker install keeps failing, I will keep trying. 

Would it be possible to deploy this to something else online? Heroku, DigitalOcean, or google cloud? I would much rather have it that way if possible?

**Comment by openpim** [comment]
It is possible to deploy the system to any cloud where docker is working, but the idea of deploy will be the same.

What errors do you have in the log? Also what command are you using to start the system? Can you please provide the details and I can try to help you.

Thanks,
Slava Pedak

**Comment by horeca2** [comment]
> Thank you so much for the answer !! :) My docker install keeps failing, I will keep trying.
> 
> Would it be possible to deploy this to something else online? Heroku, DigitalOcean, or google cloud? I would much rather have it that way if possible?

Don't forget to change the ssh key and password to the database

``` yaml
#cloud-config
users:
  - name: pim
    ssh-authorized-keys:
      - ssh-rsa AAA....
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
ssh_pwauth: false
disable_root: true

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - postgresql 
  - postgresql-contrib
  - ufw

package_update: true
# package_upgrade: true
  
write_files:
  - content: |
      listen_addresses = '*'
    path:
      /etc/postgresql/12/main/conf.d/01pim.conf  

runcmd:
  # install docker
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
  # configure postgres
  - echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/12/main/pg_hba.conf  
  - sudo -u postgres psql -U postgres --command="ALTER USER postgres WITH PASSWORD '123';"
  - systemctl restart postgresql.service
  # configure firewall
  - ufw allow 22
  - ufw allow 80  
  - ufw enable
  # install openpim
  - curl -O https://openpim.org/sql/init.sql
  - sudo -u postgres psql -U postgres -d postgres < init.sql
  # run docker as network host mode
  - docker run -d --network=host -v /mnt:/filestorage --env OPENPIM_DATABASE_ADDRESS=127.0.0.1 --env OPENPIM_DATABASE_NAME=postgres --env OPENPIM_DATABASE_USER=postgres --env OPENPIM_DATABASE_PASSWORD=123 openpim/production:1.5
hostname: localhost
prefer_fqdn_over_hostname: false
```
